modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/impleri/dimension-skills/issues"
license = "MIT"

[[mods]]
modId = "dimensionskills"
version = "${version}"
displayName = "Dimension Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to cancel dimensional travel.
'''
#logoFile = ""

[[dependencies.dimensionskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensionskills]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensionskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensionskills]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"
